version: "3"
services:
    nginx:
        image: nginx:latest
        build: ./frontend
        ports:
          - 80:80
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
          - spring
    
    spring:
        build: ./backend
        ports:
          - 8082:8082