version: "3"
services:
    nginx:
        image: nginx:latest
        build: ./frontend
        ports:
          - 80:80
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
          - ./frontend/build
        depends_on:
          - spring
    
    spring:
      build: ./backend
      ports:
        - 8080:8080