version: "3"
services:
    web:
        image: nginx:latest
        # build: /mnt/c/hotsixturtles/nginx
        ports:
          - 80:80
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
          - ./front/dist
        depends_on:
          - application

    react:
      volumes:
        - ${PWD}/frontend:/app
      build:
        context: ${PWD}/frontend
        dockerfile: ${PWD}/frontend/Dockerfile
      ports:
        - 3000:3000
    
    spring:
      build:
        context: ${PWD}/backend
        dockerfile: ${PWD}/backend/Dockerfile
      ports:
        - 8080:8080